export const EVENT_CONFIG = {
  eventName: "ENGINEER 2.0",
  edition: "2026 EDITION",
  tagline: "THINK. DESIGN. BUILD. TRANSFORM.",
  eventDate: "15 SEPTEMBER 2026",
  eventDay: "Tuesday",
  eventTime: "09:30 AM – 05:30 PM IST",
  venue: "Main University Auditorium & Advanced Engineering Labs",
  collegeName: "Apex Institute of Technology & Engineering Sciences",
  locationCity: "Bengaluru, Karnataka, India",
  registrationUrl: "#register",
  contactEmail: "engineersday@engineer2-0.org",
  supportHotline: "+91 (080) 4590-2026",
  socialLinks: {
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    x: "https://x.com",
    youtube: "https://youtube.com",
  },
  systemStatus: {
    version: "2.0.26",
    status: "ONLINE",
    build: "PROD_REL_0915",
    latency: "12ms",
  },
  registrationOpen: true,
  maxParticipants: 1500,
  currentRegistrations: 1142,
};
